import { Header } from '@/components/layout/Header';
import { Footer } from '@/components/layout/Footer';
import { Bot } from 'lucide-react';

export default function AboutPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Header />
      <main className="flex-1">
        <section className="py-12 sm:py-16 lg:py-20">
          <div className="container mx-auto max-w-4xl px-4 text-center sm:px-6 lg:px-8">
            <Bot className="mx-auto h-16 w-16 text-primary" />
            <h1 className="mt-4 text-4xl font-extrabold tracking-tight text-foreground sm:text-5xl font-headline">
              About Tech Insights Daily
            </h1>
            <p className="mx-auto mt-6 max-w-2xl text-lg text-muted-foreground">
              Tech Insights Daily is an experimental platform that leverages cutting-edge AI to automate content creation. Our goal is to explore the future of journalism and content pipelines.
            </p>
          </div>
        </section>
        
        <section className="container mx-auto max-w-3xl px-4 pb-12 sm:px-6 lg:px-8 sm:pb-16 lg:pb-20">
            <div className="prose prose-invert prose-lg mx-auto prose-headings:font-headline">
                <h2>Our Mission</h2>
                <p>
                    Our mission is to explore and showcase the capabilities of modern AI in the realm of content generation. We've built an automated pipeline that can identify trending topics, generate outlines, write full articles, and even perform quality checks before publishing.
                </p>
                <h2>The Tech Stack</h2>
                <ul>
                    <li><strong>Next.js:</strong> For a high-performance, server-rendered React application.</li>
                    <li><strong>Google Gemini:</strong> The AI model powering our content generation and analysis flows.</li>
                    <li><strong>Genkit:</strong> The framework used to structure and manage our AI flows.</li>
                    <li><strong>Cloudflare D1:</strong> A serverless database for storing our posts and categories.</li>
                    <li><strong>ShadCN UI & Tailwind CSS:</strong> For creating a modern and responsive user interface.</li>
                </ul>
                <h2>Disclaimer</h2>
                <p>
                    All content on this website is generated by an AI. While we strive for accuracy and quality, the articles are for demonstration purposes and may contain inaccuracies. This project is a proof-of-concept and a playground for AI-driven development.
                </p>
            </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
