import Link from 'next/link';

export function Hero() {
  return (
    <section className="relative py-20 md:py-32 isolate">
      <div
        aria-hidden="true"
        className="absolute inset-0 top-0 -z-10 grid grid-cols-2 -space-x-52 opacity-20 pointer-events-none"
      >
        <div className="h-56 bg-gradient-to-br from-primary to-purple-400 blur-[106px] dark:from-blue-700"></div>
        <div className="h-32 bg-gradient-to-r from-cyan-400 to-sky-300 blur-[106px] dark:to-indigo-600"></div>
      </div>
      <div className="container mx-auto max-w-4xl text-center px-4 sm:px-6 lg:px-8 relative z-10">
        <h1 className="text-4xl font-extrabold tracking-tight text-foreground sm:text-5xl md:text-6xl font-headline">
          Stay Ahead in Tech
        </h1>
        <p className="mt-6 text-lg leading-8 text-foreground/80 max-w-2xl mx-auto">
          Daily insights on AI, Open Source, and Web Development, curated and generated by our advanced AI pipeline.
        </p>
        <div className="mt-10 flex items-center justify-center gap-x-6">
          <Link
            href="/posts"
            className="inline-flex h-11 items-center justify-center gap-2 rounded-md bg-accent px-8 text-sm font-medium text-accent-foreground transition-colors hover:bg-accent/90"
          >
            Browse Latest Posts
          </Link>
          <Link
            href="/posts"
            className="inline-flex h-11 items-center justify-center gap-2 rounded-md border border-input bg-background px-8 text-sm font-medium transition-colors hover:bg-accent hover:text-accent-foreground"
          >
            Learn More &rarr;
          </Link>
        </div>
      </div>
    </section>
  );
}